#!/usr/syno/synoha/bin/bash

### Usage: Place renamedir into /bin
### Using the FULL PATH execute the following command to recursively rename all directories.
### find FULLPATH -type d -exec renamedir '{}' \;
### Real World example: find /volume1/Folder/1000-1099/1065\ Henry\ Dobson/ -type d -exec renamedir '{}' \;

/bin/touch /var/log/hdRename.log
LOG=/var/log/hdRename.log

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>$LOG 2>&1

echo "`date` ###  Original Folder Name: "$1""
NEWNAME=`echo "$1" | sed 's/[\\:*?\"<>|.]/_/g'`
printf "`date` ###  New Folder Name: $NEWNAME\n"
if [[ "$1" != "$NEWNAME" ]]; then
	printf "`date` ###  Moving $1 to $NEWNAME"
	mv "$1" "$NEWNAME"
fi
printf "\n\n"
