#!/usr/syno/synoha/bin/bash

### Usage: Place rename into /bin
### Using the FULL PATH execute the following command to recursively rename all directories.
### find FULLPATH -type f -exec rename '{}' \;
### Real World example: find /volume1/Folder/1000-1099/1065\ Henry\ Dobson/ -type f -exec rename '{}' \;

/bin/touch /var/log/hdRename.log
LOG=/var/log/hdRename.log

# Saves file descriptors so they can be restored to whatever they were
# before redirection or used themselves to output to whatever they were before the following redirect.
exec 3>&1 4>&2

# Restore file descriptors for particular signals.
# Not generally necessary since they should be restored when the sub-shell exits.
trap 'exec 2>&4 1>&3' 0 1 2 3

# Redirect stdout to file log.out then redirect stderr to stdout. Note that the order is important
# when you want them going to the same file. stdout must be redirected before stderr is redirected to stdout.
exec 1>>$LOG 2>&1

printf "`date` ###  Original Name: $1\n"
NEWNAME=`echo "$1" | sed 's/[\\:*?\"<>|]/_/g'`
printf "`date` ###  New Name: $NEWNAME\n"
if [[ "$1" != "$NEWNAME" ]]; then
	printf "`date` ###  Moving $1 to $NEWNAME"
	mv "$1" "$NEWNAME"
fi
printf "\n\n"
